[project]
authors = ["mcgilmore <michael_gilmore@live.com>"]
channels = ["conda-forge"]
name = "celleste"
platforms = ["osx-arm64"]
version = "0.1.3"

[tasks]
build = "cargo build --release"
start = "cargo run"
clean = "cargo clean"

[dependencies]
rust = ">=1.84.0,<1.85"
